#!/usr/bin/env python3
from __future__ import annotations
import sys as _v243611_sys
_v243611_sys.dont_write_bytecode=True
import argparse,hashlib,json,math,time
from pathlib import Path
import numpy as np
import pandas as pd
from v24_36_12_release import HERE,RELEASE,PREFIX,AUDIT_SUBDIR
from v24_36_12_io import SCHEMAS,write_acquisition_outputs,finalize_metadata
import v24_36_12_model as vm
import v24_36_12_process_reference as pref
import v24_36_12_complete_kernel as ck
import claritas_tardiis_core_v24_36 as core

AUDIT_CUDA=r'''
extern "C" {
#define RF_NMECH 6
#define RF_NTRANS 6
#define RF_NCLASS 5
#define RF_NPAIR 5

__device__ float rf_u(unsigned int* s,int* draws){(*draws)++;return rnd_uniform(s);}
__device__ void rf_microfacet(unsigned int* s,int* draws,float alpha,float bx,float by,float bz,float vx,float vy,float vz,int sign,float* mx,float* my,float* mz){
    *mx=bx;*my=by;*mz=bz;if(alpha<=0.0f)return;float t1x,t1y,t1z,t2x,t2y,t2z;perpendicular_basis(bx,by,bz,&t1x,&t1y,&t1z,&t2x,&t2y,&t2z);const float sig=0.7071067811865475f*alpha;
    for(int a=0;a<8;++a){float u1=fmaxf(rf_u(s,draws),1e-12f),u2=rf_u(s,draws),mag=sqrtf(-2.0f*logf(u1)),g1=mag*cosf(2.0f*PI_F*u2),g2=mag*sinf(2.0f*PI_F*u2);float nx=bx+sig*g1*t1x+sig*g2*t2x,ny=by+sig*g1*t1y+sig*g2*t2y,nz=bz+sig*g1*t1z+sig*g2*t2z;normalize3(&nx,&ny,&nz);float d=dot3(vx,vy,vz,nx,ny,nz);if((sign<0&&d<-1e-6f)||(sign>0&&d>1e-6f)){*mx=nx;*my=ny;*mz=nz;return;}}
}
__device__ int rf_macro_tir(float vx,float vy,float vz,float nx,float ny,float nz,float np,float nm){float c=fminf(fmaxf(dot3(vx,vy,vz,nx,ny,nz),0.0f),1.0f);float e=np/nm;return e*e*fmaxf(0.0f,1.0f-c*c)>=1.0f;}
__device__ float rf_beckmann_D(float mx,float my,float mz,float nx,float ny,float nz,float alpha){float c=dot3(mx,my,mz,nx,ny,nz);if(c<=0.0f||alpha<=0.0f)return 0.0f;float t2=fmaxf(0.0f,1.0f-c*c)/(c*c);return expf(-t2/(alpha*alpha))/(PI_F*alpha*alpha*c*c*c*c);}
__device__ float rf_smith_G1(float vx,float vy,float vz,float mx,float my,float mz,float nx,float ny,float nz,float alpha){float vn=dot3(vx,vy,vz,nx,ny,nz),vm=dot3(vx,vy,vz,mx,my,mz);if(fabsf(vn)<=1e-12f||vm*vn<=0.0f)return 0.0f;float c=fabsf(vn),ss=sqrtf(fmaxf(0.0f,1.0f-c*c));if(ss<=1e-12f||alpha<=0.0f)return 1.0f;float a=c/(alpha*ss);if(a>=12.0f)return 1.0f;float den=1.0f+erff(a)+expf(-a*a)/(a*sqrtf(PI_F));return 2.0f/den;}
__device__ int rf_next_macro_tir(float x,float y,float z,float cx,float cy,float cz,float vx,float vy,float vz,float radius,float np,float nm){float rx=x-cx,ry=y-cy,rz=z-cz;float chord=-2.0f*dot3(rx,ry,rz,vx,vy,vz);if(chord<=1e-12f)return -1;float xx=x+chord*vx,yy=y+chord*vy,zz=z+chord*vz;float nx=(xx-cx)/radius,ny=(yy-cy)/radius,nz=(zz-cz)/radius;normalize3(&nx,&ny,&nz);return rf_macro_tir(vx,vy,vz,nx,ny,nz,np,nm);}
__device__ void rf_pair_store(int cat,int sid,int order,int macro_tir,int rough_tir,int fb,int geom_tir,int compatible,float n1,float n2,float ix,float iy,float iz,float gx,float gy,float gz,float mx,float my,float mz,float fox,float foy,float foz,float ox,float oy,float oz,float rr,float gr,float ep,float compat,unsigned int* written,float* F,int* I){
    if(cat<0||cat>=RF_NPAIR)return;if(atomicCAS(&written[cat],0u,1u)!=0u)return;long long b=(long long)cat*21LL;F[b+0]=n1;F[b+1]=n2;F[b+2]=ix;F[b+3]=iy;F[b+4]=iz;F[b+5]=gx;F[b+6]=gy;F[b+7]=gz;F[b+8]=mx;F[b+9]=my;F[b+10]=mz;F[b+11]=fox;F[b+12]=foy;F[b+13]=foz;F[b+14]=ox;F[b+15]=oy;F[b+16]=oz;F[b+17]=rr;F[b+18]=gr;F[b+19]=ep;F[b+20]=compat;long long q=(long long)cat*8LL;I[q+0]=sid;I[q+1]=order;I[q+2]=macro_tir;I[q+3]=rough_tir;I[q+4]=fb;I[q+5]=geom_tir;I[q+6]=compatible;I[q+7]=cat;
}

__device__ int rf_extended_trace(unsigned int* state,int* draws,float nm,float np,float kp,float wl,float alpha,float radius,int prod_lim,int diag_lim,float* x,float* y,float* z,float* vx,float* vy,float* vz,float* path,int* pr,int* per,int* pir,int* pab,int* entered,int* cap_checkpoint,unsigned int* cpstate,float* cpx,float* cpy,float* cpz,float* cpvx,float* cpvy,float* cpvz,float* cppath,int* cppr,int* cpper,int* cppir,int* cppab,
unsigned int* reached,unsigned int* macro_order,unsigned int* fallback_order,unsigned int* tir_escape_order,unsigned int* tir_outside_order,unsigned int* tir_tir_order,unsigned int* trans,unsigned int* fbclass,unsigned int* cand_count,unsigned int* cand_compat,unsigned int* cand_incompat,float* cand_mass,float* rej_mass,float* rej_tir_mass,
unsigned int* pair_written,float* pairF,int* pairI,int sid){
    *entered=0;*cap_checkpoint=0;if(radius<=0.0f)return 1;
    float rho=sqrtf(fminf(fmaxf(rf_u(state,draws),0.0f),0.99999994f)),ci=sqrtf(fmaxf(0.0f,1.0f-rho*rho)),phi=rf_u(state,draws)*2.0f*PI_F;
    float e1x,e1y,e1z,e2x,e2y,e2z;perpendicular_basis(*vx,*vy,*vz,&e1x,&e1y,&e1z,&e2x,&e2y,&e2z);float qx=cosf(phi)*e1x+sinf(phi)*e2x,qy=cosf(phi)*e1y+sinf(phi)*e2y,qz=cosf(phi)*e1z+sinf(phi)*e2z;float gnx=-ci*(*vx)+rho*qx,gny=-ci*(*vy)+rho*qy,gnz=-ci*(*vz)+rho*qz;normalize3(&gnx,&gny,&gnz);float cx=*x-radius*gnx,cy=*y-radius*gny,cz=*z-radius*gnz;
    float onx=gnx,ony=gny,onz=gnz;rf_microfacet(state,draws,alpha,gnx,gny,gnz,*vx,*vy,*vz,-1,&onx,&ony,&onz);float a,b,c;float cio=(alpha>0.0f)?fminf(fmaxf(-dot3(*vx,*vy,*vz,onx,ony,onz),0.0f),1.0f):ci;int rok=refract3(*vx,*vy,*vz,onx,ony,onz,nm,np,&a,&b,&c);if(!rok||dot3(a,b,c,gnx,gny,gnz)>=-1e-7f){onx=gnx;ony=gny;onz=gnz;cio=ci;rok=refract3(*vx,*vy,*vz,onx,ony,onz,nm,np,&a,&b,&c);}float R=fresnel_R_complex(cio,nm,0.0f,np,kp);if(rf_u(state,draws)<R){float ra,rb,rc;reflect3(*vx,*vy,*vz,onx,ony,onz,&ra,&rb,&rc);*vx=ra;*vy=rb;*vz=rc;(*pr)++;(*per)++;return 1;}if(!rok)return 3;*entered=1;*vx=a;*vy=b;*vz=c;
    float aa=(wl>0.0f&&kp>0.0f)?4.0f*PI_F*kp/wl:0.0f;int prev_state=-1,prev_mech=-1;
    for(int k=0;k<diag_lim;++k){atomicAdd(&reached[k],1u);float rx=*x-cx,ry=*y-cy,rz=*z-cz;float chord=-2.0f*dot3(rx,ry,rz,*vx,*vy,*vz);if(chord<=1e-12f)return 3;if(aa>0.0f){float sv=expf(-aa*chord);if(rf_u(state,draws)>sv){*x+=chord*(*vx);*y+=chord*(*vy);*z+=chord*(*vz);*path+=chord;(*pab)++;return 2;}}
        *x+=chord*(*vx);*y+=chord*(*vy);*z+=chord*(*vz);*path+=chord;float nox=(*x-cx)/radius,noy=(*y-cy)/radius,noz=(*z-cz)/radius;normalize3(&nox,&noy,&noz);int macro=rf_macro_tir(*vx,*vy,*vz,nox,noy,noz,np,nm);if(macro)atomicAdd(&macro_order[k],1u);
        if(prev_state>=0){int tid=(prev_state==0?(macro==0?0:1):(macro==0?2:3));atomicAdd(&trans[tid*RF_NMECH+prev_mech],1u);if(prev_state==1&&macro==0)atomicAdd(&tir_outside_order[k],1u);if(prev_state==1&&macro==1)atomicAdd(&tir_tir_order[k],1u);}
        float rnx=nox,rny=noy,rnz=noz;rf_microfacet(state,draws,alpha,nox,noy,noz,*vx,*vy,*vz,+1,&rnx,&rny,&rnz);float crough=(alpha>0.0f)?fminf(fmaxf(dot3(*vx,*vy,*vz,rnx,rny,rnz),0.0f),1.0f):fminf(fmaxf(dot3(*vx,*vy,*vz,nox,noy,noz),0.0f),1.0f);float eta=np/nm,rs2=eta*eta*fmaxf(0.0f,1.0f-crough*crough);int rough_tir=rs2>=1.0f;float rta=0,rtb=0,rtc=0;int rough_ok=refract3(*vx,*vy,*vz,-rnx,-rny,-rnz,np,nm,&rta,&rtb,&rtc);float compat=rough_ok?dot3(rta,rtb,rtc,nox,noy,noz):-1.0f;int rough_compatible=rough_ok&&compat>1e-7f;float Rrough=rough_tir?1.0f:fresnel_R_complex(crough,np,kp,nm,0.0f);float emass=rough_tir?0.0f:(1.0f-Rrough);int cb=2*k+macro;if(!rough_tir){atomicAdd(&cand_count[cb],1u);atomicAdd(&cand_mass[cb],emass);if(rough_compatible)atomicAdd(&cand_compat[cb],1u);else{atomicAdd(&cand_incompat[cb],1u);atomicAdd(&rej_mass[cb],emass);}}
        float ta=rta,tb=rtb,tc=rtc;int fb=0;if(!rough_compatible){rnx=nox;rny=noy;rnz=noz;fb=1;rough_ok=refract3(*vx,*vy,*vz,-rnx,-rny,-rnz,np,nm,&ta,&tb,&tc);}float cgeom=fminf(fmaxf(dot3(*vx,*vy,*vz,nox,noy,noz),0.0f),1.0f);float cfinal=fb?cgeom:crough;float fs2=eta*eta*fmaxf(0.0f,1.0f-cfinal*cfinal);int geom_tir=eta*eta*fmaxf(0.0f,1.0f-cgeom*cgeom)>=1.0f;int final_tir=fs2>=1.0f;if(fb){atomicAdd(&fallback_order[k],1u);int cls=rough_tir?(geom_tir?2:3):(geom_tir?0:1);atomicAdd(&fbclass[k*RF_NCLASS+cls],1u);if(!rough_tir&&!rough_compatible&&geom_tir)atomicAdd(&rej_tir_mass[cb],emass);}
        float Rfinal=final_tir?1.0f:fresnel_R_complex(cfinal,np,kp,nm,0.0f);int transmit=0;if(!final_tir&&rough_ok){float u=rf_u(state,draws);if(u>=Rfinal)transmit=1;}
        if(transmit){int mech=(alpha<=0.0f)?5:(fb?3:1);int tid=macro?5:4;atomicAdd(&trans[tid*RF_NMECH+mech],1u);if(macro)atomicAdd(&tir_escape_order[k],1u);if(alpha>0.0f&&!fb)rf_pair_store(1,sid,k,macro,rough_tir,fb,geom_tir,rough_compatible,np,nm,*vx,*vy,*vz,nox,noy,noz,rnx,rny,rnz,rta,rtb,rtc,ta,tb,tc,Rrough,Rfinal,emass,compat,pair_written,pairF,pairI);*vx=ta;*vy=tb;*vz=tc;return 1;}
        float rra,rrb,rrc;reflect3(*vx,*vy,*vz,rnx,rny,rnz,&rra,&rrb,&rrc);float rough_ra=rra,rough_rb=rrb,rough_rc=rrc;int rfb=0;if(dot3(rra,rrb,rrc,nox,noy,noz)>=-1e-7f){reflect3(*vx,*vy,*vz,nox,noy,noz,&rra,&rrb,&rrc);rfb=1;atomicAdd(&fallback_order[k],1u);atomicAdd(&fbclass[k*RF_NCLASS+4],1u);}int mech=(alpha<=0.0f)?4:((fb||rfb)?2:0);
        if(alpha>0.0f&&!fb&&!rfb)rf_pair_store(0,sid,k,macro,rough_tir,0,geom_tir,rough_compatible,np,nm,*vx,*vy,*vz,nox,noy,noz,rnx,rny,rnz,rough_ra,rough_rb,rough_rc,rra,rrb,rrc,Rrough,Rfinal,emass,compat,pair_written,pairF,pairI);
        if(alpha>0.0f&&!rough_tir&&!rough_compatible&&geom_tir) {rf_pair_store(2,sid,k,macro,rough_tir,1,geom_tir,0,np,nm,*vx,*vy,*vz,nox,noy,noz,rnx,rny,rnz,rta,rtb,rtc,rra,rrb,rrc,Rrough,Rfinal,emass,compat,pair_written,pairF,pairI);rf_pair_store(4,sid,k,macro,rough_tir,1,geom_tir,0,np,nm,*vx,*vy,*vz,nox,noy,noz,rnx,rny,rnz,rta,rtb,rtc,rra,rrb,rrc,Rrough,Rfinal,emass,compat,pair_written,pairF,pairI);}
        int next=rf_next_macro_tir(*x,*y,*z,cx,cy,cz,rra,rrb,rrc,radius,np,nm);if(alpha>0.0f&&macro==0&&next==1&&!fb&&!rfb)rf_pair_store(3,sid,k,macro,rough_tir,0,geom_tir,rough_compatible,np,nm,*vx,*vy,*vz,nox,noy,noz,rnx,rny,rnz,rough_ra,rough_rb,rough_rc,rra,rrb,rrc,Rrough,Rfinal,emass,compat,pair_written,pairF,pairI);
        *vx=rra;*vy=rrb;*vz=rrc;(*pr)++;(*pir)++;prev_state=macro;prev_mech=mech;if(*pir==prod_lim){*cap_checkpoint=1;*cpstate=*state;*cpx=*x;*cpy=*y;*cpz=*z;*cpvx=*vx;*cpvy=*vy;*cpvz=*vz;*cppath=*path;*cppr=*pr;*cpper=*per;*cppir=*pir;*cppab=*pab;}if(*pir==diag_lim){atomicAdd(&reached[diag_lim],1u);return 4;}
    }return 4;
}

__global__ void reciprocity_fallback_kernel(const int SAMPLES,const float NM,const float NP,const float KP,const float WL,const float ALPHA,const float RADIUS,const int PROD_LIM,const int DIAG_LIM,const unsigned int SEED,
unsigned char* PROD_STATUS,unsigned char* EXT_STATUS,unsigned char* ENTERED,unsigned char* PROD_CAP,unsigned char* STATE_MATCH,unsigned char* COUNTER_MATCH,float* DIR_ERR,float* POS_ERR,unsigned short* REFLECTIONS,
unsigned int* REACHED,unsigned int* MACRO_ORDER,unsigned int* FALLBACK_ORDER,unsigned int* TIR_ESCAPE_ORDER,unsigned int* TIR_OUTSIDE_ORDER,unsigned int* TIR_TIR_ORDER,unsigned int* TRANS,unsigned int* FBCLASS,unsigned int* CAND_COUNT,unsigned int* CAND_COMPAT,unsigned int* CAND_INCOMPAT,float* CAND_MASS,float* REJ_MASS,float* REJ_TIR_MASS,unsigned int* PAIR_WRITTEN,float* PAIR_F,int* PAIR_I){
    int sid=(int)(blockDim.x*blockIdx.x+threadIdx.x);if(sid>=SAMPLES)return;unsigned int init=SEED+(unsigned int)sid*74729u+13u;if(init==0)init=1u;unsigned int sp=init,se=init;float xp=0,yp=0,zp=0,vxp=0,vyp=1,vzp=0,ipp=0;int prp=0,perp=0,pirp=0,pabsp=0;int ps=sphere_fresnel_interaction_3d(&sp,NM,NP,KP,WL,ALPHA,RADIUS,PROD_LIM-1,&xp,&yp,&zp,&vxp,&vyp,&vzp,&ipp,&prp,&perp,&pirp,&pabsp);
    float xe=0,ye=0,ze=0,vxe=0,vye=1,vze=0,ipe=0;int pre=0,pere=0,pire=0,pabse=0,draws=0,entered=0,cpv=0,cppr=0,cpper=0,cppir=0,cppab=0;unsigned int cps=0;float cpx=0,cpy=0,cpz=0,cpvx=0,cpvy=0,cpvz=0,cppath=0;
    int es=rf_extended_trace(&se,&draws,NM,NP,KP,WL,ALPHA,RADIUS,PROD_LIM,DIAG_LIM,&xe,&ye,&ze,&vxe,&vye,&vze,&ipe,&pre,&pere,&pire,&pabse,&entered,&cpv,&cps,&cpx,&cpy,&cpz,&cpvx,&cpvy,&cpvz,&cppath,&cppr,&cpper,&cppir,&cppab,REACHED,MACRO_ORDER,FALLBACK_ORDER,TIR_ESCAPE_ORDER,TIR_OUTSIDE_ORDER,TIR_TIR_ORDER,TRANS,FBCLASS,CAND_COUNT,CAND_COMPAT,CAND_INCOMPAT,CAND_MASS,REJ_MASS,REJ_TIR_MASS,PAIR_WRITTEN,PAIR_F,PAIR_I,sid);
    float de=0,pe=0;int sm=0,cm=0,cap=0;if(ps==1||ps==2){float dx=vxp-vxe,dy=vyp-vye,dz=vzp-vze;de=sqrtf(dx*dx+dy*dy+dz*dz);float ax=xp-xe,ay=yp-ye,az=zp-ze;pe=sqrtf(ax*ax+ay*ay+az*az);sm=(sp==se);cm=(prp==pre&&perp==pere&&pirp==pire&&pabsp==pabse);}else if(cpv&&pirp==PROD_LIM){float dx=vxp-cpvx,dy=vyp-cpvy,dz=vzp-cpvz;de=sqrtf(dx*dx+dy*dy+dz*dz);float ax=xp-cpx,ay=yp-cpy,az=zp-cpz;pe=sqrtf(ax*ax+ay*ay+az*az);sm=(sp==cps);cm=(prp==cppr&&perp==cpper&&pirp==cppir&&pabsp==cppab);cap=(sm&&cm&&de<=2e-6f&&pe<=2e-6f);}
    PROD_STATUS[sid]=(unsigned char)ps;EXT_STATUS[sid]=(unsigned char)es;ENTERED[sid]=(unsigned char)entered;PROD_CAP[sid]=(unsigned char)cap;STATE_MATCH[sid]=(unsigned char)sm;COUNTER_MATCH[sid]=(unsigned char)cm;DIR_ERR[sid]=de;POS_ERR[sid]=pe;REFLECTIONS[sid]=(unsigned short)min(pire,65535);
}

__global__ void visibility_kernel(const int N,const float C,const float ALPHA,const unsigned int SEED,float* OUT){int j=(int)(blockDim.x*blockIdx.x+threadIdx.x);if(j>=N)return;unsigned int s=SEED+(unsigned int)j*11939u+7u;if(s==0)s=1u;float u1=fmaxf(rnd_uniform(&s),1e-12f),u2=rnd_uniform(&s),mag=sqrtf(-2.0f*logf(u1)),sig=0.7071067811865475f*ALPHA,sx=sig*mag*cosf(2.0f*PI_F*u2),sy=sig*mag*sinf(2.0f*PI_F*u2);float mx=sx,my=sy,mz=1.0f;normalize3(&mx,&my,&mz);float ss=sqrtf(fmaxf(0.0f,1.0f-C*C)),vx=ss,vy=0.0f,vz=C;float vm=vx*mx+vz*mz;float facing=(vm>0.0f)?1.0f:0.0f;float g=rf_smith_G1(vx,vy,vz,mx,my,mz,0,0,1,ALPHA);float w=(C>1e-12f&&mz>1e-12f)?g*fabsf(vm)/(C*mz):0.0f;if(!facing||!isfinite(w))w=0.0f;long long b=(long long)j*5LL;OUT[b+0]=facing;OUT[b+1]=acosf(fminf(fmaxf(mz,-1.0f),1.0f))*180.0f/PI_F;OUT[b+2]=fabsf(vm);OUT[b+3]=mz;OUT[b+4]=w;}

__global__ void fixed_microfacet_kernel(const int N,const float* V,const float* NRM,const float* M,const float* N1,const float* N2,const int* MODE,float* DIRRES,float* FRESRES,int* FOK,int* ROK){int j=(int)(blockDim.x*blockIdx.x+threadIdx.x);if(j>=N)return;float ix=V[3*j],iy=V[3*j+1],iz=V[3*j+2],mx=M[3*j],my=M[3*j+1],mz=M[3*j+2];float ox=0,oy=0,oz=0,rx=0,ry=0,rz=0;if(MODE[j]==0){reflect3(ix,iy,iz,mx,my,mz,&ox,&oy,&oz);reflect3(-ox,-oy,-oz,mx,my,mz,&rx,&ry,&rz);FOK[j]=1;ROK[j]=1;}else{int ok=refract3(ix,iy,iz,-mx,-my,-mz,N1[j],N2[j],&ox,&oy,&oz);FOK[j]=ok;if(ok){ROK[j]=refract3(-ox,-oy,-oz,mx,my,mz,N2[j],N1[j],&rx,&ry,&rz);}else ROK[j]=0;}float dx=rx+ix,dy=ry+iy,dz=rz+iz;DIRRES[j]=(FOK[j]&&ROK[j])?sqrtf(dx*dx+dy*dy+dz*dz):1.0f;float ci=fabsf(ix*mx+iy*my+iz*mz),co=fabsf(ox*mx+oy*my+oz*mz);float f1=fresnel_R_complex(ci,N1[j],0.0f,N2[j],0.0f);float f2=(MODE[j]==0)?fresnel_R_complex(co,N1[j],0.0f,N2[j],0.0f):fresnel_R_complex(co,N2[j],0.0f,N1[j],0.0f);FRESRES[j]=fabsf(f1-f2);}
}
'''

MECH_NAMES=['accepted_rough_reflection','accepted_rough_escape','fallback_geom_reflection','fallback_geom_escape','smooth_reflection','smooth_escape']
TRANS_NAMES=['outside_to_outside','outside_to_tir','tir_to_outside','tir_to_tir','outside_to_escape','tir_to_escape']
FB_CLASS_NAMES=['rough_non_tir_incompatible_to_geom_tir','rough_non_tir_incompatible_to_geom_non_tir','rough_tir_to_geom_tir','rough_tir_to_geom_non_tir','rough_reflection_incompatible_to_geom_reflection']
PAIR_NAMES=['accepted_rough_reflection','accepted_rough_escape','fallback_geom_tir','outside_to_tir','candidate_escape_rejected']

def _build_model(cfg):return core.TardiisForwardModel(**vm.model_kwargs(cfg))
def _compile(cp):
    t=time.perf_counter();m=cp.RawModule(code=core.CUDA_SRC+AUDIT_CUDA,options=('-std=c++11',));funcs={n:m.get_function(n) for n in ('reciprocity_fallback_kernel','visibility_kernel','fixed_microfacet_kernel')};cp.cuda.Stream.null.synchronize();return funcs,time.perf_counter()-t

def _run_bin(cp,func,props,n,seed,alpha,prod,diag):
    n=int(n);threads=128;blocks=(n+threads-1)//threads
    def z(sz,d):return cp.zeros(int(sz),dtype=d)
    prodst=z(n,cp.uint8);ext=z(n,cp.uint8);entered=z(n,cp.uint8);cap=z(n,cp.uint8);sm=z(n,cp.uint8);cm=z(n,cp.uint8);de=z(n,cp.float32);pe=z(n,cp.float32);refl=z(n,cp.uint16)
    reached=z(diag+1,cp.uint32);macro=z(diag,cp.uint32);fbord=z(diag,cp.uint32);tesc=z(diag,cp.uint32);tout=z(diag,cp.uint32);ttir=z(diag,cp.uint32);trans=z(6*6,cp.uint32);fbclass=z(diag*5,cp.uint32);cand=z(diag*2,cp.uint32);ccomp=z(diag*2,cp.uint32);cinc=z(diag*2,cp.uint32);cmass=z(diag*2,cp.float32);rmass=z(diag*2,cp.float32);rtmass=z(diag*2,cp.float32);pw=z(5,cp.uint32);pf=z(5*21,cp.float32);pi=z(5*8,cp.int32)
    args=(np.int32(n),np.float32(props['n_medium']),np.float32(props['n_particle']),np.float32(props['k_particle']),np.float32(props['wavelength']),np.float32(alpha),np.float32(props['radius']),np.int32(prod),np.int32(diag),np.uint32(seed),prodst,ext,entered,cap,sm,cm,de,pe,refl,reached,macro,fbord,tesc,tout,ttir,trans,fbclass,cand,ccomp,cinc,cmass,rmass,rtmass,pw,pf,pi)
    func((blocks,),(threads,),args);cp.cuda.Stream.null.synchronize()
    arr={'prod_status':prodst,'ext_status':ext,'entered':entered,'prod_cap':cap,'state_match':sm,'counter_match':cm,'dir_err':de,'pos_err':pe,'reflections':refl}
    out={k:cp.asnumpy(v) for k,v in arr.items()};out['reached']=cp.asnumpy(reached);out['macro']=cp.asnumpy(macro);out['fallback_order']=cp.asnumpy(fbord);out['tir_escape_order']=cp.asnumpy(tesc);out['tir_outside_order']=cp.asnumpy(tout);out['tir_tir_order']=cp.asnumpy(ttir);out['trans']=cp.asnumpy(trans).reshape(6,6);out['fbclass']=cp.asnumpy(fbclass).reshape(diag,5);out['cand']=cp.asnumpy(cand).reshape(diag,2);out['ccomp']=cp.asnumpy(ccomp).reshape(diag,2);out['cinc']=cp.asnumpy(cinc).reshape(diag,2);out['cmass']=cp.asnumpy(cmass).reshape(diag,2);out['rmass']=cp.asnumpy(rmass).reshape(diag,2);out['rtmass']=cp.asnumpy(rtmass).reshape(diag,2);out['pair_written']=cp.asnumpy(pw);out['pair_f']=cp.asnumpy(pf).reshape(5,21);out['pair_i']=cp.asnumpy(pi).reshape(5,8);return out

def _run_visibility(cp,func,c,alpha,n,seed,bins):
    threads=128;blocks=(n+threads-1)//threads;O=cp.zeros(n*5,cp.float32);func((blocks,),(threads,),(np.int32(n),np.float32(c),np.float32(alpha),np.uint32(seed),O));cp.cuda.Stream.null.synchronize();a=cp.asnumpy(O).reshape(n,5);face=a[:,0]>0.5;w=a[:,4].astype(float);wf=w.sum();theta=a[:,1]
    hist_raw,_=np.histogram(theta[face],bins=bins);hist_w,_=np.histogram(theta,bins=bins,weights=w);z=float(face.mean());G1=pref.smith_G1_beckmann(np.array([math.sqrt(max(0,1-c*c)),0,c]),np.array([0,0,1.]),np.array([0,0,1.]),alpha)
    row={'release':RELEASE,'incident_cos_macro':float(c),'samples':int(n),'raw_facing_count':int(face.sum()),'raw_backfacing_count':int((~face).sum()),'raw_facing_fraction':z,'smith_G1':float(G1),'vndf_normalization_estimate':float(w.mean()),'current_conditioned_mean_abs_v_dot_m':float(a[face,2].mean()) if face.any() else np.nan,'vndf_weighted_mean_abs_v_dot_m':float(np.sum(w*a[:,2])/wf) if wf>0 else np.nan,'current_conditioned_mean_m_dot_n':float(a[face,3].mean()) if face.any() else np.nan,'vndf_weighted_mean_m_dot_n':float(np.sum(w*a[:,3])/wf) if wf>0 else np.nan,'eight_try_exhaustion_estimate':float((1-z)**8),'classification':'raw Beckmann NDF D(m)|m.n| with facing rejection; not a Smith visible-normal distribution'}
    hs=[];den=max(int(face.sum()),1);wden=max(wf,1e-30)
    for j in range(len(bins)-1):
        cf=float(hist_raw[j]/den);vf=float(hist_w[j]/wden);hs.append({'release':RELEASE,'incident_cos_macro':float(c),'theta_lo_deg':float(bins[j]),'theta_hi_deg':float(bins[j+1]),'raw_facing_count':int(hist_raw[j]),'current_conditioned_fraction':cf,'vndf_weighted_fraction':vf,'absolute_fraction_difference':abs(cf-vf)})
    st={'release':RELEASE,'incident_cos_macro':float(c),'samples':int(n),'raw_facing_fraction':z,'eight_try_exhaustion_estimate':float((1-z)**8),'current_conditioned_mean_microfacet_angle_deg':float(theta[face].mean()) if face.any() else np.nan,'vndf_weighted_mean_microfacet_angle_deg':float(np.sum(w*theta)/wf) if wf>0 else np.nan,'vndf_normalization':float(w.mean()),'current_vs_vndf_l1_histogram':float(sum(x['absolute_fraction_difference'] for x in hs)),'sampler_classification':'current sampler is facing-conditioned raw NDF, not VNDF'}
    return row,hs,st

def _run_fixed(cp,func,alpha,tol):
    cases=pref.fixed_cases(alpha);V=[];N=[];M=[];A=[];B=[];MODE=[];names=[]
    for name,mode,vin,n,m,n1,n2 in cases:names.append(name);V.append(vin);N.append(n);M.append(m);A.append(n1);B.append(n2);MODE.append(0 if mode=='reflection' else 1)
    Vc=cp.asarray(np.asarray(V,np.float32).reshape(-1));Nc=cp.asarray(np.asarray(N,np.float32).reshape(-1));Mc=cp.asarray(np.asarray(M,np.float32).reshape(-1));Ac=cp.asarray(np.asarray(A,np.float32));Bc=cp.asarray(np.asarray(B,np.float32));Ic=cp.asarray(np.asarray(MODE,np.int32));nn=len(cases);dr=cp.zeros(nn,cp.float32);fr=cp.zeros(nn,cp.float32);fo=cp.zeros(nn,cp.int32);ro=cp.zeros(nn,cp.int32);func(((nn+31)//32,),(32,),(np.int32(nn),Vc,Nc,Mc,Ac,Bc,Ic,dr,fr,fo,ro));cp.cuda.Stream.null.synchronize();dr,fr,fo,ro=[cp.asnumpy(x) for x in (dr,fr,fo,ro)];cpu={r['case_name']:r for r in pref.fixed_microfacet_rows(alpha)};rows=[]
    for j,(name,mode,vin,n,m,n1,n2) in enumerate(cases):
        cr=cpu[name];passed=bool(fo[j] and ro[j] and dr[j]<=tol['fixed_microfacet_direction_l2'] and fr[j]<=tol['fresnel_reciprocity_abs'] and cr['bsdf_reciprocity_relative_error']<=tol['microfacet_bsdf_reciprocity_rel']);rows.append({'release':RELEASE,'case_name':name,'mode':mode,'n1':n1,'n2':n2,'incident_cos_macro':abs(float(np.dot(vin,n))),'microfacet_cos_macro':float(np.dot(m,n)),'forward_ok':bool(fo[j]),'reverse_ok':bool(ro[j]),'forward_reverse_direction_l2':float(dr[j]),'fresnel_reverse_abs':float(fr[j]),'bsdf_reciprocity_relative_error':float(cr['bsdf_reciprocity_relative_error']),'expected_relation':cr['expected_relation'],'passed':passed})
    return rows

def _pair_rows(material,idx,q,out):
    rows=[]
    for cat,name in enumerate(PAIR_NAMES):
        if int(out['pair_written'][cat])==0:continue
        f=out['pair_f'][cat];ii=out['pair_i'][cat];rows.append({'release':RELEASE,'material':material,'bin_index':idx,'qsca':q,'sample_id':int(ii[0]),'reflection_order':int(ii[1]),'category':name,'macro_tir_before':int(ii[2]),'rough_tir':int(ii[3]),'fallback':int(ii[4]),'geom_tir':int(ii[5]),'rough_compatible':int(ii[6]),'n1':float(f[0]),'n2':float(f[1]),'ix':float(f[2]),'iy':float(f[3]),'iz':float(f[4]),'gnx':float(f[5]),'gny':float(f[6]),'gnz':float(f[7]),'mnx':float(f[8]),'mny':float(f[9]),'mnz':float(f[10]),'fox':float(f[11]),'foy':float(f[12]),'foz':float(f[13]),'final_ox':float(f[14]),'final_oy':float(f[15]),'final_oz':float(f[16]),'rough_fresnel_R':float(f[17]),'geom_fresnel_R':float(f[18]),'rough_escape_probability':float(f[19]),'compatibility_metric':float(f[20])})
    return rows

def _rows_bin(material,idx,host,ew,cw,out,samples,mode,diag):
    q=float(host['qsca'][idx]);reached=out['reached'];macro=out['macro'];fb=out['fallback_order'];trans=out['trans'];tirb=int(macro.sum());outb=int(reached[:diag].sum()-tirb);fallbacks=int(fb.sum());accepted=max(int(reached[:diag].sum())-fallbacks,0);cand=int(out['cand'].sum());cin=int(out['cinc'].sum());cmass=float(out['cmass'].sum());rmass=float(out['rmass'].sum());rtmass=float(out['rtmass'].sum());cap=int(out['prod_cap'].sum());cens=int(np.sum(out['ext_status']==4))
    # transition counts summed over mechanisms
    t=trans.sum(axis=1).astype(int)
    flux={'release':RELEASE,'material':material,'bin_index':idx,'diameter_m':float(host['diameter_m'][idx]),'qsca':q,'event_rate_weight':float(ew[idx]),'projected_csa_weight':float(cw[idx]),'samples':samples,'outside_to_tir':int(t[1]),'tir_to_outside':int(t[2]),'tir_to_escape':int(t[5]),'tir_to_tir':int(t[3]),'outside_to_outside':int(t[0]),'outside_to_escape':int(t[4]),'tir_boundary_count':tirb,'outside_boundary_count':outb,'fallback_boundaries':fallbacks,'accepted_rough_boundaries':accepted if mode=='rough' else 0,'candidate_escape_states':cand,'candidate_escape_rejected':cin,'candidate_escape_rejected_to_geom_tir':int(sum(out['fbclass'][:,0])),'candidate_escape_probability_mass':cmass,'rejected_escape_probability_mass':rmass,'rejected_to_geom_tir_probability_mass':rtmass,'production_cap_hits':cap,'other_production_failure_count':int(np.sum(out['prod_status']==0))-cap,'diagnostic_censored':cens,'max_prefix_direction_l2':float(np.max(out['dir_err'])) if samples else 0.0,'max_prefix_position_l2':float(np.max(out['pos_err'])) if samples else 0.0,'prefix_rng_mismatch_fraction':float(np.mean(out['state_match']==0)) if samples else 0.0,'prefix_counter_mismatch_fraction':float(np.mean(out['counter_match']==0)) if samples else 0.0}
    tm=[]
    for ti,tname in enumerate(TRANS_NAMES):
        denom=(outb if ti in (0,1,4) else tirb)
        for mi,mname in enumerate(MECH_NAMES):
            c=int(trans[ti,mi]);tm.append({'release':RELEASE,'material':material,'bin_index':idx,'qsca':q,'event_rate_weight':float(ew[idx]),'mechanism':mname,'from_state':'outside' if ti in (0,1,4) else 'tir','to_state':('outside' if ti in (0,2) else 'tir' if ti in (1,3) else 'escape'),'count':c,'fraction_of_from_state':float(c/denom) if denom else np.nan})
    fbc=[];cer=[];surv=[];haz=[]
    maxk=min(diag,max(int(np.max(out['reflections']))+2,2))
    for k in range(maxk):
        rc=int(reached[k]);mc=int(macro[k]);fc=int(fb[k]);surv.append({'release':RELEASE,'material':material,'bin_index':idx,'qsca':q,'reflection_order':k,'reached_count':rc,'macro_tir_count':mc,'macro_tir_fraction_of_reached':float(mc/rc) if rc else np.nan,'fallback_count':fc,'fallback_fraction_of_reached':float(fc/rc) if rc else np.nan})
        e=int(out['tir_escape_order'][k]);oo=int(out['tir_outside_order'][k]);tt=int(out['tir_tir_order'][k]);haz.append({'release':RELEASE,'material':material,'bin_index':idx,'qsca':q,'reflection_order':k,'macro_tir_boundary_count':mc,'escape_count':e,'outside_next_count':oo,'tir_next_count':tt,'escape_hazard':float(e/mc) if mc else np.nan,'leave_basin_hazard':float((e+oo)/mc) if mc else np.nan,'fallback_count':fc,'fallback_fraction':float(fc/rc) if rc else np.nan})
        totalfb=int(out['fbclass'][k].sum())
        for ci,name in enumerate(FB_CLASS_NAMES):
            cc=int(out['fbclass'][k,ci]);fbc.append({'release':RELEASE,'material':material,'bin_index':idx,'qsca':q,'reflection_order':k,'class_name':name,'count':cc,'fraction_of_fallbacks_at_order':float(cc/totalfb) if totalfb else np.nan})
        for state in (0,1):
            ccount=int(out['cand'][k,state]);comp=int(out['ccomp'][k,state]);inc=int(out['cinc'][k,state]);m=float(out['cmass'][k,state]);r=float(out['rmass'][k,state]);rt=float(out['rtmass'][k,state]);cer.append({'release':RELEASE,'material':material,'bin_index':idx,'qsca':q,'reflection_order':k,'macro_tir_state':state,'rough_non_tir_count':ccount,'rough_non_tir_compatible_count':comp,'rough_non_tir_incompatible_count':inc,'candidate_escape_probability_mass':m,'rejected_escape_probability_mass':r,'rejected_to_geom_tir_probability_mass':rt,'rejection_fraction_count':float(inc/ccount) if ccount else np.nan,'rejection_fraction_probability_mass':float(r/m) if m>0 else np.nan})
    entry=int(np.sum((out['prod_status']==1)&(out['entered']==0)));escaped=int(np.sum(out['ext_status']==1));absorbed=int(np.sum(out['ext_status']==2));num=int(np.sum(out['ext_status']==3));resolved=escaped+absorbed+num+cens;pc={'release':RELEASE,'material':material,'bin_index':idx,'qsca':q,'samples':samples,'entry_reflection_count':entry,'escaped_count':escaped,'absorbed_count':absorbed,'numerical_geometry_failure_count':num,'diagnostic_censored_count':cens,'resolved_or_censored_count':resolved,'count_closure_error':int(resolved-samples),'production_cap_hits':cap,'production_cap_loss_fraction':float(cap/samples)}
    return flux,tm,fbc,cer,surv,haz,pc

def _aggregate_flux(tables):
    by=pd.DataFrame(tables['macro_tir_flux_by_bin']);out=[]
    for mat,g in by.groupby('material'):
        # only rough rows are written to flux table; controls are separate
        w=g.event_rate_weight.to_numpy(float);w=w/w.sum()
        def wr(num,den):
            a=g[num].to_numpy(float);b=g[den].to_numpy(float);r=np.divide(a,b,out=np.zeros_like(a),where=b>0);return float(np.sum(w*r))
        out.append({'release':RELEASE,'material':mat,'event_weighted_outside_to_tir_per_boundary':wr('outside_to_tir','outside_boundary_count'),'event_weighted_tir_to_outside_per_tir_boundary':wr('tir_to_outside','tir_boundary_count'),'event_weighted_tir_to_escape_per_tir_boundary':wr('tir_to_escape','tir_boundary_count'),'event_weighted_tir_to_tir_per_tir_boundary':wr('tir_to_tir','tir_boundary_count'),'event_weighted_candidate_escape_rejection_fraction':wr('candidate_escape_rejected','candidate_escape_states'),'event_weighted_rejected_escape_probability_mass_fraction':wr('rejected_escape_probability_mass','candidate_escape_probability_mass'),'event_weighted_rejected_to_geom_tir_mass_fraction':wr('rejected_to_geom_tir_probability_mass','candidate_escape_probability_mass'),'event_weighted_fallback_fraction':float(np.sum(w*(g.fallback_boundaries/(g.tir_boundary_count+g.outside_boundary_count).replace(0,np.nan)).fillna(0.0))),'event_weighted_production_cap_fraction':float(np.sum(w*g.production_cap_hits/g.samples)),'event_weighted_diagnostic_censored_fraction':float(np.sum(w*g.diagnostic_censored/g.samples))})
    tables['macro_tir_flux_aggregate'].extend(out)

def _build_macro_tir_reciprocal_flux(tables):
    df=pd.DataFrame(tables['complete_kernel_reciprocity_pairs'])
    if df.empty:return
    for mat in ('loess','kaolin'):
        g=df[(df.material==mat)&(df.pair_kind=='macro_tir_primary')]
        if g.empty:continue
        w=g.event_rate_weight.to_numpy(float);w=w/w.sum()
        fw=float(np.sum(w*g.forward_weighted_flux));rw=float(np.sum(w*g.reverse_weighted_flux));se=float(math.sqrt(np.sum((w*g.standard_error.to_numpy(float))**2)));rel=abs(fw-rw)/max(abs(fw),abs(rw),1e-30);z=abs(fw-rw)/se if se>0 else (0.0 if fw==rw else float('inf'))
        fcnt=float(g.forward_total_count.sum());rcnt=float(g.reverse_total_count.sum())
        tables['macro_tir_reciprocal_flux'].append({'release':RELEASE,'material':mat,'event_weighted_outside_to_tir_flux':fw,'event_weighted_tir_to_outside_flux':rw,'relative_residual':rel,'z_score':z,'accepted_forward_fraction':float(g.forward_accepted_rough_count.sum()/fcnt) if fcnt else np.nan,'fallback_forward_fraction':float(g.forward_fallback_count.sum()/fcnt) if fcnt else np.nan,'accepted_reverse_fraction':float(g.reverse_accepted_rough_count.sum()/rcnt) if rcnt else np.nan,'fallback_reverse_fraction':float(g.reverse_fallback_count.sum()/rcnt) if rcnt else np.nan,'passed':bool(rel<=0.01 or z<5.0)})

def acquire_gpu(output_dir:Path,samples_per_bin:int|None=None,host_smoke:bool=False)->dict:
    if host_smoke:return acquire_host_smoke(output_dir)
    cfg=vm.load_config();b=cfg['reciprocity_fallback_audit_v24_36_12'];tol=b['invariant_tolerances'];samples=int(samples_per_bin or b['samples_per_bin']);smooth_n=min(int(b['smooth_control_samples_per_bin']),samples);prod=int(b['production_reflection_limit']);diag=int(b['diagnostic_reflection_limit']);model=_build_model(cfg);cp=model.cp;funcs,compile_s=_compile(cp);ck_func,ck_compile_s=ck.compile_kernel(cp,core.CUDA_SRC);tables={k:[] for k in SCHEMAS}
    alpha=float(model.particle_surface_beckmann_alpha);tables['fixed_microfacet_reversibility'].extend(_run_fixed(cp,funcs['fixed_microfacet_kernel'],alpha,tol));bins=np.asarray(b['visibility_theta_bins_deg'],float)
    for j,c in enumerate(b['visibility_incident_cosines']):
        row,hist,st=_run_visibility(cp,funcs['visibility_kernel'],float(c),alpha,int(b['visibility_samples_per_angle']),int(b['seed'])+900000+j*1009,bins);tables['microfacet_visibility_audit'].append(row);tables['microfacet_visibility_histogram'].extend(hist);tables['stochastic_microfacet_reciprocity'].append(st)
    coverage={};control_rows=[]
    for mi,mat in enumerate(('loess','kaolin')):
        prep=model._prepare_gpu_particle_physics(mat,1.0,None,'mass_fraction');host=prep['host'];ew,cw=vm.event_and_csa_weights(host);coverage[mat]=0
        for idx,qv in enumerate(host['qsca']):
            q=float(qv)
            if not vm.qsca_in_audit(q,cfg):continue
            coverage[mat]+=1;props={'n_medium':model.n_water,'n_particle':float(host['n_real'][idx]),'k_particle':float(host['k_imag'][idx]),'wavelength':model.particle_wavelength,'radius':float(host['radius_m'][idx])};seed=int(b['seed'])+mi*1000003+idx*10007
            rough=_run_bin(cp,funcs['reciprocity_fallback_kernel'],props,samples,seed,alpha,prod,diag);flux,tm,fbc,cer,surv,haz,pc=_rows_bin(mat,idx,host,ew,cw,rough,samples,'rough',diag);tables['macro_tir_flux_by_bin'].append(flux);tables['macro_tir_transition_matrix'].extend(tm);tables['fallback_transition_classes'].extend(fbc);tables['candidate_escape_rejection'].extend(cer);tables['trapped_basin_survival'].extend(surv);tables['trapped_basin_escape_hazard'].extend(haz);tables['probability_conservation'].append(pc);tables['reciprocity_pairs'].extend(_pair_rows(mat,idx,q,rough)); ckout=ck.run_gpu_bin(cp,ck_func,props['n_medium'],props['n_particle'],0.0,alpha,samples,seed+333331);tables['complete_kernel_reciprocity_pairs'].extend(ck.pair_rows(mat,idx,q,float(ew[idx]),props['n_medium'],props['n_particle'],samples,ckout));tables['fallback_flux_decomposition'].extend(ck.flux_decomposition_rows(mat,idx,q,float(ew[idx]),samples,ckout))
            smooth=_run_bin(cp,funcs['reciprocity_fallback_kernel'],props,smooth_n,seed+7717,0.0,prod,diag);sf,_,_,_,_,_,spc=_rows_bin(mat,idx,host,ew,cw,smooth,smooth_n,'smooth',diag)
            rough_tir_frac=flux['tir_boundary_count']/max(flux['tir_boundary_count']+flux['outside_boundary_count'],1);smooth_tir_frac=sf['tir_boundary_count']/max(sf['tir_boundary_count']+sf['outside_boundary_count'],1)
            control_rows.append({'release':RELEASE,'material':mat,'bin_index':idx,'diameter_m':float(host['diameter_m'][idx]),'qsca':q,'event_rate_weight':float(ew[idx]),'rough_production_cap_fraction':float(flux['production_cap_hits']/samples),'smooth_production_cap_fraction':float(sf['production_cap_hits']/smooth_n),'rough_mean_reflections':float(np.mean(rough['reflections'])),'smooth_mean_reflections':float(np.mean(smooth['reflections'])),'rough_macro_tir_boundary_fraction':float(rough_tir_frac),'smooth_macro_tir_boundary_fraction':float(smooth_tir_frac),'rough_fallback_fraction':float(flux['fallback_boundaries']/max(flux['tir_boundary_count']+flux['outside_boundary_count'],1)),'smooth_fallback_fraction':float(sf['fallback_boundaries']/max(sf['tir_boundary_count']+sf['outside_boundary_count'],1))})
    tables['rough_smooth_control'].extend(control_rows);_aggregate_flux(tables);tables['reciprocity_residuals'].extend(pref.reconstruct_pair_rows(tables['reciprocity_pairs'],alpha,tol['fixed_microfacet_direction_l2'],tol['fresnel_reciprocity_abs'],tol['microfacet_bsdf_reciprocity_rel'])); tables['complete_kernel_reciprocity_summary'].extend(ck.summarize_pairs(pd.DataFrame(tables['complete_kernel_reciprocity_pairs']))); _build_macro_tir_reciprocal_flux(tables)
    paths=write_acquisition_outputs(output_dir,tables,finalize_metadata({'gpu_acquisition_complete':True,'cuda_compile_seconds':compile_s,'complete_kernel_cuda_compile_seconds':ck_compile_s,'samples_per_bin':samples,'smooth_control_samples_per_bin':smooth_n,'production_reflection_limit':prod,'diagnostic_reflection_limit':diag,'materials':['loess','kaolin'],'audited_bins':coverage,'production_core_cuda_sha256':hashlib.sha256(core.CUDA_SRC.encode()).hexdigest(),'audit_cuda_sha256':hashlib.sha256((AUDIT_CUDA+ck.COMPLETE_KERNEL_CUDA).encode()).hexdigest(),'particle_k_forced_zero':True,'roughness_rms_slope_deg':25.0,'microfacet_sampler_classification':'raw Beckmann D(m)|m.n| sampled by Gaussian slopes, then facing rejection up to 8 attempts; no Smith VNDF or explicit masking/shadowing term in production kernel'}));return {'paths':paths,'compile_seconds':compile_s+ck_compile_s,'tables':tables}

def acquire_host_smoke(output_dir:Path)->dict:
    tables={k:[] for k in SCHEMAS};tables['fixed_microfacet_reversibility'].extend(pref.fixed_microfacet_rows())
    for c in (0.05,0.5,1.0):
        tables['microfacet_visibility_audit'].append({'release':RELEASE,'incident_cos_macro':c,'samples':100,'raw_facing_count':80,'raw_backfacing_count':20,'raw_facing_fraction':0.8,'smith_G1':0.9,'vndf_normalization_estimate':1.0,'current_conditioned_mean_abs_v_dot_m':0.4,'vndf_weighted_mean_abs_v_dot_m':0.5,'current_conditioned_mean_m_dot_n':0.8,'vndf_weighted_mean_m_dot_n':0.75,'eight_try_exhaustion_estimate':2.56e-6,'classification':'host smoke'});tables['stochastic_microfacet_reciprocity'].append({'release':RELEASE,'incident_cos_macro':c,'samples':100,'raw_facing_fraction':0.8,'eight_try_exhaustion_estimate':2.56e-6,'current_conditioned_mean_microfacet_angle_deg':20.0,'vndf_weighted_mean_microfacet_angle_deg':25.0,'vndf_normalization':1.0,'current_vs_vndf_l1_histogram':0.2,'sampler_classification':'host smoke'})
        tables['microfacet_visibility_histogram'].append({'release':RELEASE,'incident_cos_macro':c,'theta_lo_deg':0.0,'theta_hi_deg':90.0,'raw_facing_count':80,'current_conditioned_fraction':1.0,'vndf_weighted_fraction':1.0,'absolute_fraction_difference':0.0})
    for mat in ('loess','kaolin'):
        for idx,q in enumerate((1.01,2.0)):
            flux={'release':RELEASE,'material':mat,'bin_index':idx,'diameter_m':(idx+1)*1e-6,'qsca':q,'event_rate_weight':0.5,'projected_csa_weight':0.5,'samples':16,'outside_to_tir':2,'tir_to_outside':1,'tir_to_escape':1,'tir_to_tir':4,'outside_to_outside':3,'outside_to_escape':5,'tir_boundary_count':6,'outside_boundary_count':10,'fallback_boundaries':5,'accepted_rough_boundaries':11,'candidate_escape_states':4,'candidate_escape_rejected':2,'candidate_escape_rejected_to_geom_tir':2,'candidate_escape_probability_mass':1.0,'rejected_escape_probability_mass':0.5,'rejected_to_geom_tir_probability_mass':0.5,'production_cap_hits':1,'other_production_failure_count':0,'diagnostic_censored':0,'max_prefix_direction_l2':0.0,'max_prefix_position_l2':0.0,'prefix_rng_mismatch_fraction':0.0,'prefix_counter_mismatch_fraction':0.0};tables['macro_tir_flux_by_bin'].append(flux)
            for ti,tname in enumerate(TRANS_NAMES):tables['macro_tir_transition_matrix'].append({'release':RELEASE,'material':mat,'bin_index':idx,'qsca':q,'event_rate_weight':0.5,'mechanism':MECH_NAMES[0],'from_state':'outside' if ti in (0,1,4) else 'tir','to_state':'outside' if ti in (0,2) else 'tir' if ti in (1,3) else 'escape','count':1,'fraction_of_from_state':0.1})
            for k in range(3):
                tables['trapped_basin_survival'].append({'release':RELEASE,'material':mat,'bin_index':idx,'qsca':q,'reflection_order':k,'reached_count':8-k,'macro_tir_count':max(0,4-k),'macro_tir_fraction_of_reached':0.5,'fallback_count':max(0,3-k),'fallback_fraction_of_reached':0.3})
                tables['trapped_basin_escape_hazard'].append({'release':RELEASE,'material':mat,'bin_index':idx,'qsca':q,'reflection_order':k,'macro_tir_boundary_count':max(1,4-k),'escape_count':1,'outside_next_count':1,'tir_next_count':2,'escape_hazard':0.25,'leave_basin_hazard':0.5,'fallback_count':2,'fallback_fraction':0.25})
                for cl in FB_CLASS_NAMES:tables['fallback_transition_classes'].append({'release':RELEASE,'material':mat,'bin_index':idx,'qsca':q,'reflection_order':k,'class_name':cl,'count':0,'fraction_of_fallbacks_at_order':0.0})
                for st in (0,1):tables['candidate_escape_rejection'].append({'release':RELEASE,'material':mat,'bin_index':idx,'qsca':q,'reflection_order':k,'macro_tir_state':st,'rough_non_tir_count':2,'rough_non_tir_compatible_count':1,'rough_non_tir_incompatible_count':1,'candidate_escape_probability_mass':0.5,'rejected_escape_probability_mass':0.25,'rejected_to_geom_tir_probability_mass':0.25,'rejection_fraction_count':0.5,'rejection_fraction_probability_mass':0.5})
            tables['probability_conservation'].append({'release':RELEASE,'material':mat,'bin_index':idx,'qsca':q,'samples':16,'entry_reflection_count':2,'escaped_count':14,'absorbed_count':0,'numerical_geometry_failure_count':0,'diagnostic_censored_count':0,'resolved_or_censored_count':16,'count_closure_error':0,'production_cap_hits':1,'production_cap_loss_fraction':0.0625})
            tables['rough_smooth_control'].append({'release':RELEASE,'material':mat,'bin_index':idx,'diameter_m':(idx+1)*1e-6,'qsca':q,'event_rate_weight':0.5,'rough_production_cap_fraction':0.0625,'smooth_production_cap_fraction':0.0,'rough_mean_reflections':5.0,'smooth_mean_reflections':0.1,'rough_macro_tir_boundary_fraction':0.4,'smooth_macro_tir_boundary_fraction':0.0,'rough_fallback_fraction':0.3,'smooth_fallback_fraction':0.0}); _ck={'src':np.array([4,4,4,4],dtype=np.uint64),'refl_total':np.array([[2,1,1,0],[1,2,1,0],[1,1,2,1],[0,0,1,2]],dtype=np.uint64).ravel(),'refl_accept':np.array([[2,1,1,0],[1,2,1,0],[1,1,2,1],[0,0,1,2]],dtype=np.uint64).ravel(),'refl_fallback':np.zeros(16,dtype=np.uint64),'escape_total':np.array([2,2,1,0],dtype=np.uint64),'escape_accept':np.array([2,2,1,0],dtype=np.uint64),'escape_fallback':np.zeros(4,dtype=np.uint64),'entry_total':np.array([2,2,1,0],dtype=np.uint64),'entry_accept':np.array([2,2,1,0],dtype=np.uint64),'entry_fallback':np.zeros(4,dtype=np.uint64),'candidate_mass':np.array([1.0]),'rejected_mass':np.array([0.2]),'rejected_tir_mass':np.array([0.2])};tables['complete_kernel_reciprocity_pairs'].extend(ck.pair_rows(mat,idx,q,0.5,1.333,1.59,16,_ck));tables['fallback_flux_decomposition'].extend(ck.flux_decomposition_rows(mat,idx,q,0.5,16,_ck))
    _aggregate_flux(tables);tables['complete_kernel_reciprocity_summary'].extend(ck.summarize_pairs(pd.DataFrame(tables['complete_kernel_reciprocity_pairs'])));_build_macro_tir_reciprocal_flux(tables);paths=write_acquisition_outputs(output_dir,tables,finalize_metadata({'gpu_acquisition_complete':False,'host_smoke':True,'production_reflection_limit':65,'diagnostic_reflection_limit':512,'materials':['loess','kaolin']}));return {'paths':paths,'tables':tables,'compile_seconds':0.0}

def main():
    ap=argparse.ArgumentParser();ap.add_argument('--output-dir',default='results');ap.add_argument('--samples-per-bin',type=int);ap.add_argument('--host-smoke',action='store_true');a=ap.parse_args();r=acquire_host_smoke(Path(a.output_dir)) if a.host_smoke else acquire_gpu(Path(a.output_dir),a.samples_per_bin);print(json.dumps({'release':RELEASE,'compile_seconds':r['compile_seconds'],'diagnostic_only':True},indent=2))
if __name__=='__main__':main()
